### ISSUE TITLE
SRA upload

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS-CoV-2-RBD_MAP_RBD-nano-vax-NHP1#1]
@ajgreaney, for the SRA upload, can you make a copy of the the `data/barcode_runs.csv` file that has just the "new" data that should be uploaded here, and then I'll do that. You can put it in a file called `SRA_uploads/barcode_runs_RBD-nano-vax-NHP1.csv`.

**Comment by ajgreaney** [comment]
@jbloom done!

**Comment by jbloom** [comment]
@ajgreaney, these data are uploaded to the SRA. Here is the BioSample accession: https://github.com/jbloomlab/SARS-CoV-2-RBD_MAP_RBD-nano-vax-NHP1/blob/main/SRA_upload/upload_config.yaml#L2
